"""Configuration constants for the PlutoSDR backscatter receiver."""

RX_URI = "ip:192.168.2.1"
FREQ_HZ = 2.48e9
SAMPLE_RATE = 1e6
RX_GAIN_MODE: str = "manual"
RX_GAIN_DB = 40.0
RX_BUFFER_SIZE = 65536       # 3.8 Hz/bin — 263 bins between carrier and ±1 kHz sideband
ADC_FULL_SCALE = 2048.0
TIME_SAMPLES = 1200
SPECTRUM_SPAN_HZ = 150000.0
FFT_AVG_ALPHA = 0.1           # ~10-frame memory — ~1s response, good noise rejection
EXCITER_SEARCH_MIN_HZ = 500.0   # ignore near-DC bins
EXCITER_SEARCH_MAX_HZ = 40000.0 # prevent false lock on far-out noise peaks
CENTERED_SPAN_HZ = 8000.0
WATERFALL_ROWS = 120
WATERFALL_BINS = 512          # lower interpolation cost per frame
WATERFALL_DYN_RANGE_DB = 28.0 # wider range avoids center saturation and preserves discrete lines
DC_BLOCK_ALPHA = 0.9998       # cutoff ≈ 32 Hz — well below 1 kHz signal
RX_RF_BANDWIDTH = 200_000     # AD9361 on-chip analog LPF — rejects noise outside 200 kHz
ENABLE_FOCUSED_FILTER = False # default off: avoids filter transients/blueout artifacts
FOCUSED_PASSBAND_HZ = 2500.0
SIDEBAND_OFFSET_KHZ = 1.0     # 1 kHz subcarrier offset
SIDEBAND_WINDOW_HZ = 30.0     # ±30 Hz at 3.8 Hz/bin = ±8 bins — tight enough to avoid noise peaks
SNR_LOCK_THRESHOLD_DB = 20.0  # minimum SNR for a reliable backscatter decode
ENV_Y_SMOOTH_ALPHA = 0.15     # envelope y-limit smoothing (higher = more responsive)
ENV_Y_MIN_SPAN = 0.01         # minimum y-span for envelope plot stability
CENTERED_FREQ_SMOOTH_BINS = 3 # lighter smoothing to keep sidebands sharp
WATERFALL_ROW_BLEND = 0.75    # favor current frame; less temporal blur
BIT_DURATION_MS = 50.0
SUBCARRIER_HZ = 1000.0
CONTINUOUS_ON_TEST = False
ALL_ONES_TEST = True
BIT_NCC_THRESHOLD = 0.20       # fixed fallback threshold for chip decisions
ADAPTIVE_BIT_NCC_THRESHOLD = True
BIT_NCC_NOISE_ALPHA = 0.05     # EMA speed for |NCC| noise tracking (lower = steadier)
BIT_NCC_MARGIN = 0.02          # keep threshold close to floor so repeated-1 chips survive
BIT_NCC_THRESHOLD_MIN = 0.10 if ALL_ONES_TEST else 0.14
BIT_NCC_THRESHOLD_MAX = 0.30   # allow headroom above floor while still preventing runaway
DEMOD_FILTER_PASSBAND_HZ = 3500.0
DEMOD_ENV_SMOOTH_SAMPLES = 48  # moving-average smoothing for envelope display only
CHIP_VIEW_HISTORY = 96         # chips shown in the lower demod panel (96 * 50 ms = 4.8 s)
PREAMBLE_BYTES = b"\xAA\xAA"
SYNC_BYTES = b"\xD3\x91"
PAYLOAD_BYTES = b"\xFF\xFF\xFF\xFF" if ALL_ONES_TEST else b"OPEN"
PACKET_DECODE_ENABLED = not CONTINUOUS_ON_TEST
REPETITION_CHIPS = 3
SAMPLES_PER_CHIP = int(SAMPLE_RATE * (BIT_DURATION_MS / 1000.0))
LOGICAL_BIT_DURATION_MS = BIT_DURATION_MS * REPETITION_CHIPS
SAMPLES_PER_LOGICAL_BIT = SAMPLES_PER_CHIP * REPETITION_CHIPS
MAJORITY_ONES_THRESHOLD = (REPETITION_CHIPS // 2) + 1  # symmetric majority for packet-mode zeros in preamble/sync
ENV_WINDOW_CHIPS = 1  # 1 chip = 50 ms. 3 chips (=150 ms) exceeds current RX_BUFFER_SIZE at 1 Msps.
NCC_DISPLAY_ALPHA = 0.2
NCC_ENTER_THRESHOLD = 0.13  # observed EMA often peaks around 0.14–0.17; allow practical lock entry
NCC_EXIT_THRESHOLD = 0.07   # retain hysteresis to prevent rapid lock churn
NCC_ENTER_FRAMES = 2        # avoid requiring long consecutive runs in fading channels
NCC_EXIT_FRAMES = 8         # hold lock through short fades once acquired
NCC_SOFT_DECODE_THRESHOLD = 0.11  # decode fallback when EMA is strong but lock criteria are narrowly missed
DECODE_UNLOCK_GRACE_CHIPS = 24  # keep decode alive briefly after lock drops (~1.2 s)
PACKET_STATUS_HOLD_FRAMES = 20
TERMINAL_DEBUG_BITS_EVERY = 20
TERMINAL_DEBUG_BIT_TAIL = 64
BIT_PHASE_STEP_SAMPLES = 5000
CHIP_TIMING_TRACK_ENABLE = not CONTINUOUS_ON_TEST
CHIP_TIMING_SEARCH_SAMPLES = 1000   # +/- 1 ms at 1 Msps
CHIP_TIMING_STEP_SAMPLES = 500      # evaluate early/center/late windows
CHIP_TIMING_TRACK_MARGIN = 0.02     # only retime when metric is confidently above threshold
CHIP_TIMING_MIN_ADVANTAGE = 0.01    # require meaningful gain over center to shift timing
CHIP_TIMING_DRIFT_ALPHA = 0.15      # smoothing for chip-stride adaptation
CHIP_TIMING_STRIDE_MIN_SCALE = 0.90
CHIP_TIMING_STRIDE_MAX_SCALE = 1.10
CONTINUOUS_ON_THRESHOLD_ALPHA = 0.05
CONTINUOUS_ON_THRESHOLD_SCALE = 0.55
CONTINUOUS_ON_THRESHOLD_MAX = 0.22
CHIP_BISTABLE_ENABLE = True
CHIP_DECISION_HYSTERESIS = 0.0
CHIP_RISE_CONFIRM_CHIPS = 1
CHIP_FALL_CONFIRM_CHIPS = 1
CHIP_STICKY_WINDOW_CHIPS = 24
CHIP_STICKY_ONE_RATIO = 0.80
CHIP_STICKY_FALL_CONFIRM_CHIPS = 1
CONTINUOUS_ON_FALL_CONFIRM_CHIPS = 1
PHASE_HISTORY_BITS = 128
PACKET_DECODE_TOP_PHASES = 2
PACKET_MERGE_GAP_BITS = 6
PACKET_CANDIDATE_SETTLE_BITS = 24 if ALL_ONES_TEST else 8
HEADER_MAX_BIT_ERRORS = 12 if ALL_ONES_TEST else 10
PREAMBLE_MIN_TRANSITIONS = 6   # 0xAAAA has 15 ideal transitions; relax for timing-misaligned preamble
PAYLOAD_MAX_BIT_ERRORS = 1 if ALL_ONES_TEST else 3
