#include <msp430.h>
#include <stdint.h>

/*
 * Secure Backscatter Transmitter (MSP430G2553).
 *
 * Packet:    0xAA 0x7E 0x55 0x55 0x55 0x55   (48 bits, MSB first).
 *            Test pattern: alternating bits in payload so any corruption
 *            (stuck-high / stuck-low / wrong-stride) is obvious on the air.
 * Encoding:  OOK of a 1 kHz subcarrier. '1' = subcarrier on, '0' = off.
 * Bit time:  50 ms (100 CCR0 toggle events at 500 us each).
 *
 * The subcarrier is generated by Timer_A0 in toggle mode on P1.1 and runs
 * continuously. Bits are gated by (dis)connecting the pin via P1SEL so
 * subcarrier phase stays continuous across bit boundaries.
 */

#define PACKET_LENGTH               6U
#define SUBCARRIER_HZ_NOMINAL       1000U
#define BIT_SUBCARRIER_TICKS        100U    /* 100 * 500us = 50 ms */
#define GAP_BETWEEN_PACKETS_TICKS   4000U   /* 2 s */

const uint8_t packet[PACKET_LENGTH] = { 0xAA, 0x7E, 0x55, 0x55, 0x55, 0x55 };

/* Block for N CCR0 toggle events. Locks bit timing to the subcarrier
 * timer so there is no software-delay drift. */
static void wait_subcarrier_ticks(uint16_t ticks) {
    while (ticks--) {
        while ((TA0CCTL0 & CCIFG) == 0) { /* spin */ }
        TA0CCTL0 &= ~CCIFG;
    }
}

static void subcarrier_on(void) {
    P1SEL |= BIT1;
    P1OUT |= BIT6;          /* status LED: bit = '1' */
}

static void subcarrier_off(void) {
    P1SEL &= ~BIT1;
    P1OUT &= ~(BIT1 | BIT6);
}

static void transmit_byte(uint8_t byte) {
    int8_t i;
    for (i = 7; i >= 0; i--) {
        if ((byte >> i) & 0x01) subcarrier_on();
        else                    subcarrier_off();
        wait_subcarrier_ticks(BIT_SUBCARRIER_TICKS);
    }
}

static void transmit_packet(void) {
    uint8_t i;
    P1OUT |= BIT0;          /* packet-active LED */
    for (i = 0; i < PACKET_LENGTH; i++) transmit_byte(packet[i]);
    subcarrier_off();
    P1OUT &= ~BIT0;
}

int main(void) {
    WDTCTL = WDTPW | WDTHOLD;

    /* Load 1 MHz DCO calibration. If CAL bytes are erased, blink slowly
     * instead of transmitting at an unknown clock rate. */
    if (CALBC1_1MHZ == 0xFF || CALDCO_1MHZ == 0xFF) {
        P1DIR |= BIT0;
        while (1) { P1OUT ^= BIT0; __delay_cycles(100000); }
    }
    DCOCTL  = 0;
    BCSCTL1 = CALBC1_1MHZ;
    DCOCTL  = CALDCO_1MHZ;

    P1DIR  |=  (BIT0 | BIT1 | BIT6);
    P1OUT  &= ~(BIT0 | BIT1 | BIT6);
    P1SEL  &= ~BIT1;        /* start with subcarrier gated off */
    P1SEL2 &= ~BIT1;

    /* Timer_A0: SMCLK / up mode / toggle on CCR0.
     * CCR0 = SMCLK / (2 * f_sub) - 1 = 1e6 / 2000 - 1 = 499. */
    TA0CCR0   = (1000000U / (2U * SUBCARRIER_HZ_NOMINAL)) - 1U;
    TA0CCTL0  = OUTMOD_4;
    TA0CTL    = TASSEL_2 | MC_1 | TACLR;
    TA0CCTL0 &= ~CCIFG;

    while (1) {
        transmit_packet();
        wait_subcarrier_ticks(GAP_BETWEEN_PACKETS_TICKS);
    }
}
